workflows/pennsieve.aws.nf

fix: reference correct script

---

taskRunner/init.py

fix: formats json

---

taskRunner/main.py

fix: updates processor code

---

main.go
taskRunner/cleanup.py
taskRunner/cleanup_local.py
taskRunner/multi_stage.py
taskRunner/multi_stage_local.py
workflows/pennsieve.aws.nf

- file cleanup
- fix for same message being processed multiple times

feature: cleanup files

---

main.go

-  increases visibility timeout

fix: increase visibility timeout

---

taskRunner/multi_stage.py

- increases max attempts for longer running tasks

fix: increases max attempts

---

main.go

- creates workspace and sub-directories

fix: creates workspace and sub-directories

---

.github/workflows/docker-image.yml

- adds github actions to push docker image to public registry.

feature: adds github actions

---

main.go

fix: adds debug statements

---

.github/workflows/docker-image.yml
README.md

fix: updates to push tag as well

---

.github/workflows/docker-image.yml

- address deprecation warnings

fix: address deprecation warnings

---

.github/workflows/docker-image.yml

fix: reinstate tag

---

taskRunner/config.py
taskRunner/multi_stage.py

fix: updates config and passes params

---

taskRunner/multi_stage.py

fix: passes subnet ids

---

taskRunner/multi_stage.py

- starts task for visualization

fix: starts task for visualization

---

taskRunner/multi_stage.py

fix: update start service logic

---

taskRunner/multi_stage.py

fix: specifies cluster

---

taskRunner/api.py
taskRunner/finalise.py
taskRunner/init.py
taskRunner/multi_stage.py

**ClickUp Ticket:** [868cdq5ce](https://app.clickup.com/t/868cdq5ce)
**Related PR:** https://github.com/Pennsieve/integration-service/pull/63
- Uses the new `PUT /workflows/instances/{id}/processor/{processorId}/status` endpoint to update an individual processor status
- Uses the `PUT /workflows/instances/{id}/status` endpoint instead of the deprecated `PUT /workflows/instances` endpoint to finalize the workflow instance

868cdq5ce refactor workflow instance status

---

dev.env.sample
main.go
taskRunner/finalise.py
taskRunner/multi_stage.py
test/main.go
workflows/pennsieve.aws.nf

- starts visualization service task based on param and refactors

fix: updates start service

---

.github/workflows/docker-image.yml

fix: reinstate latest

---

taskRunner/config.py
taskRunner/finalise.py
taskRunner/multi_stage.py

- reverts visualization related changes

fix: reverts visualization related changes

---

.github/workflows/docker-image.yml
taskRunner/config.py
taskRunner/finalise.py
taskRunner/logger.py

- reinstate visualization changes for testing

fix: reinstate visualization changes for testing

---

.github/workflows/docker-image.yml
main.go
taskRunner/api.py
taskRunner/config.py
taskRunner/finalise.py
taskRunner/multi_stage.py
workflows/pennsieve.aws.nf

- calls to update the processor status are failing causing workflows to not complete
- this is likely due to a token expiring - added token refreshing logic

fix: status errors

---

taskRunner/multi_stage.py

- adds some error handling if no exitCode is returned

fix: adds some error handling if no exitCode is returned

---

taskRunner/multi_stage.py

Related: https://app.clickup.com/t/868dmcmfa
- adds tags to fargate task on `run_task`

feature: Cost Analysis of workflows

---

taskRunner/multi_stage.py

- passes in correct environment variable

fix: passes in the correct variable

---

taskRunner/multi_stage.py

fixes typo

---

taskRunner/multi_stage.py

- sets project tag to cluster name

fix: sets project tag to cluster name

---

main.go
taskRunner/multi_stage.py
test/main.go
workflows/pennsieve.aws.nf

- adds a resources folder to enable static resources to be accessed without download

feature: adds a resources folder

---

taskRunner/api.py
taskRunner/init.py
taskRunner/multi_stage.py
test/main.go

- support `n` processors (using old stack)

feature: support n processors

---

main.go
taskRunner/multi_stage.py
test/main.go
workflows/pennsieve.aws.nf

fix: adds a workdir

---

taskRunner/multi_stage.py

fix: refactors dirs

---

taskRunner/multi_stage.py

fix: cleanup and refactor

---

go.mod
taskRunner/multi_stage.py

- `go mod tidy` and returning of log statement

fix: go mod tidy and returning of log statement

---

taskRunner/multi_stage.py

- refactoring to represent app levels

fix: refactoring to represent app levels

---

main.go

fix: updates logic

---

main.go

fix: updates to 2hrs to test

---

main.go

fix: use correct host
